<a href="https://colab.research.google.com/github/raju2309/EY_GDS/blob/main/Python_Numpy_WithExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#The first thing we want to do is import numpy.
import numpy as np

In [2]:
#Let us first define a Python list containing the ages of 6 people.
age = [23,34,55,76,87]
age

[23, 34, 55, 76, 87]

In [3]:
#There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use np.array(<collection>)
age1 = np.array(age)
print(type(age1))
print(age1)

<class 'numpy.ndarray'>
[23 34 55 76 87]


In [4]:
print(age1)
print("Size:\t" , age1.size)
print("Shape:\t", age1.shape)

[23 34 55 76 87]
Size:	 5
Shape:	 (5,)


In [6]:
zero_Array = np.zeros(6)
print(zero_Array)

[0. 0. 0. 0. 0. 0.]


In [11]:
#Multidimensional 
#Now let us define a new list containing the weights of these 6 people.
Weight = [92,23,45,67,87]

In [13]:
#Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.
people = np.array([age, Weight])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)


People:	 [[23 34 55 76 87]
 [92 23 45 67 87]]
Size:	 10
Shape:	 (2, 5)


In [21]:
#reshape
people = people.reshape(5,2)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)
#Note: The new shape must be the same "size" as the old shape

People:	 [[23 34]
 [55 76]
 [87 92]
 [23 45]
 [67 87]]
Size:	 10
Shape:	 (5, 2)


In [22]:
### Exercise
Val1D = [7,9,65,33,85,99]

In [25]:
Val1D = np.array(Val1D)
Val1D

array([ 7,  9, 65, 33, 85, 99])

In [24]:
Val2D = [1,2,4,2,3,0,0,5,1]

In [26]:
Val2D = np.array(Val2D)
Val2D

array([1, 2, 4, 2, 3, 0, 0, 5, 1])

In [27]:
Val2D = Val2D.reshape(3,3)
Val2D
#Exercise End

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [28]:
#Array Generation
#Instead of defining an array manually, we can ask numpy to do it for us.

#The np.arange() method creates a range of numbers with user defined steps between each.
table= np.arange(0, 55, 5)
table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [30]:
#The np.linspace() method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.
Even_spaced = np.linspace(0,50,21)
print(Even_spaced)



[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5 50. ]


In [32]:
#The .repeat() method will repeat an object you pas a specified number of times.
repeat= np.repeat(5, 10)
repeat

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [34]:
#The np.eye() functions will create an identity matrix/array for us.
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#Operations
#There are many, many operations which we can perform on arrays. Below, we demonstrate a few.
table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [36]:
print("1:", 2 * table)
print("2:", 10 +table)
print("3:", table - 1)
print("4:", table/5)
print("5:", table **2)
print("6:", table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


In [37]:
#Speed Test
#If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.
list2 = list(range(0,5001,30))
list2

[0,
 30,
 60,
 90,
 120,
 150,
 180,
 210,
 240,
 270,
 300,
 330,
 360,
 390,
 420,
 450,
 480,
 510,
 540,
 570,
 600,
 630,
 660,
 690,
 720,
 750,
 780,
 810,
 840,
 870,
 900,
 930,
 960,
 990,
 1020,
 1050,
 1080,
 1110,
 1140,
 1170,
 1200,
 1230,
 1260,
 1290,
 1320,
 1350,
 1380,
 1410,
 1440,
 1470,
 1500,
 1530,
 1560,
 1590,
 1620,
 1650,
 1680,
 1710,
 1740,
 1770,
 1800,
 1830,
 1860,
 1890,
 1920,
 1950,
 1980,
 2010,
 2040,
 2070,
 2100,
 2130,
 2160,
 2190,
 2220,
 2250,
 2280,
 2310,
 2340,
 2370,
 2400,
 2430,
 2460,
 2490,
 2520,
 2550,
 2580,
 2610,
 2640,
 2670,
 2700,
 2730,
 2760,
 2790,
 2820,
 2850,
 2880,
 2910,
 2940,
 2970,
 3000,
 3030,
 3060,
 3090,
 3120,
 3150,
 3180,
 3210,
 3240,
 3270,
 3300,
 3330,
 3360,
 3390,
 3420,
 3450,
 3480,
 3510,
 3540,
 3570,
 3600,
 3630,
 3660,
 3690,
 3720,
 3750,
 3780,
 3810,
 3840,
 3870,
 3900,
 3930,
 3960,
 3990,
 4020,
 4050,
 4080,
 4110,
 4140,
 4170,
 4200,
 4230,
 4260,
 4290,
 4320,
 4350,
 4380,
 4410,
 44

In [39]:
arr1= np.arange(0,5001,30)
arr1

array([   0,   30,   60,   90,  120,  150,  180,  210,  240,  270,  300,
        330,  360,  390,  420,  450,  480,  510,  540,  570,  600,  630,
        660,  690,  720,  750,  780,  810,  840,  870,  900,  930,  960,
        990, 1020, 1050, 1080, 1110, 1140, 1170, 1200, 1230, 1260, 1290,
       1320, 1350, 1380, 1410, 1440, 1470, 1500, 1530, 1560, 1590, 1620,
       1650, 1680, 1710, 1740, 1770, 1800, 1830, 1860, 1890, 1920, 1950,
       1980, 2010, 2040, 2070, 2100, 2130, 2160, 2190, 2220, 2250, 2280,
       2310, 2340, 2370, 2400, 2430, 2460, 2490, 2520, 2550, 2580, 2610,
       2640, 2670, 2700, 2730, 2760, 2790, 2820, 2850, 2880, 2910, 2940,
       2970, 3000, 3030, 3060, 3090, 3120, 3150, 3180, 3210, 3240, 3270,
       3300, 3330, 3360, 3390, 3420, 3450, 3480, 3510, 3540, 3570, 3600,
       3630, 3660, 3690, 3720, 3750, 3780, 3810, 3840, 3870, 3900, 3930,
       3960, 3990, 4020, 4050, 4080, 4110, 4140, 4170, 4200, 4230, 4260,
       4290, 4320, 4350, 4380, 4410, 4440, 4470, 45

In [40]:
%timeit arr1 + 5

970 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [41]:
%timeit [i + 5 for i in list2]

10.7 µs ± 72.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
#Boolean string operations can also be performed on ndarrays.
words = np.array(["ten", "nine", "eight", "seven", "six","e"])

print(np.isin(words, 'e'))

print("e" in words)
["e" in x for x in words]

[False False False False False  True]
True


[True, True, True, True, False, True]

In [48]:
#Transpose
people
people.shape = (2, 5)
print(people, "\n")
print(people.T)

[[23 34 55 76 87]
 [92 23 45 67 87]] 

[[23 92]
 [34 23]
 [55 45]
 [76 67]
 [87 87]]


In [49]:
#As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the .dtype attribute.
people.dtype

dtype('int64')

In [51]:
#What is the data type of the below ndarray?
ages_with_strings = np.array([11, 5, 8, '21', '62', '40'])
ages_with_strings

array(['11', '5', '8', '21', '62', '40'], dtype='<U21')

In [55]:
#What is the dtype of this array?
ages_with_strings = np.array([11, 5, 8, '21', '62', '40'],dtype = 'int32')
ages_with_strings

array([11,  5,  8, 21, 62, 40], dtype=int32)

In [56]:
ages_with_strings = np.array([11, 5, 8, '21', '62', '40'])
ages_with_strings

array(['11', '5', '8', '21', '62', '40'], dtype='<U21')

In [65]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 56  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 57  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 49 50  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [58]:
ages_with_strings.size

126

In [59]:
ages_with_strings.size/21

6.0

In [60]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [63]:
#The correct way to have changed the data type of the ndarray would have been to use the .astype() method, demonstrated below.
ages_with_strings = np.array([18, 9, 12, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['18' '9' '12' '32' '65' '43']
[18  9 12 32 65 43]


In [72]:
#Exercise
#Create an array of string numbers, but use dtype to make it an array of floats.
#Transpose the matrix, printing the new size and shape.
#Use the .astype() method to convert the array to boolean.

array_strings = np.array(['18', '9', '12', '32', '65', '43'],dtype='float32')
array_strings
array_strings.shape = (2,3)
array_strings
print(array_strings.T)
print(array_strings.astype('bool'))

[[18. 32.]
 [ 9. 65.]
 [12. 43.]]
[[ True  True  True]
 [ True  True  True]]


In [73]:
#Array Slicing Operations
#As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.
table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [74]:
table[0]


0

In [75]:
table[-1]

50

In [76]:
table[:4]

array([ 0,  5, 10, 15])

In [77]:
table[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [78]:
#We can also slice an n-dim ndarray., specifying the slice operation accross each axis.
print(people)
people[:3, :3]

[[23 34 55 76 87]
 [92 23 45 67 87]]


array([[23, 34, 55],
       [92, 23, 45]])

In [81]:
#Exercise
#1.Create a numpy array with 50 zeros
zeros2 =np.zeros(50)
zeros2




array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
#2.Create a np array of 2 repeated 20 times
times_20 = np.repeat(2,20)
print(times_20)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [83]:
#3.Create a numpy array from 0 to 2  π  in steps of 0.1
arr_num = np.arange(0,3.14,0.1)
print(arr_num)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1]


In [84]:
#_____For one of the arrays generated:
#4.Get the first five values
print(arr_num[0:5])

[0.  0.1 0.2 0.3 0.4]


In [93]:
#5.Get the last 3 values
print(arr_num[-3:])

[2.9 3.  3.1]


In [96]:
#6.Get the 4th value to the 7th value
print(arr_num[3])
print(arr_num[6])

#Exercise End here

0.30000000000000004
0.6000000000000001


In [97]:
#We can reverse an array by using .flip() or by using the :: operator.
table = np.flip(table)
table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [98]:
print(table[-1::-1])

[ 0  5 10 15 20 25 30 35 40 45 50]


In [99]:
#We can also use the :: operator to select steps of the original array.
print(table[0::3])#Every 3rd element starting from 0

[50 35 20  5]


In [104]:
#Exercise:
#1.Take one of the arrays you defined and Reverse it
Rev_arr = np.array([34, 12, 2, 61, 21, 25, 99])
Rev_arr
Rev_arr1 = np.flip(Rev_arr)
Rev_arr1



array([99, 25, 21, 61,  2, 12, 34])

In [105]:
#2.Only keep every 4th element.
print(Rev_arr1[0::4])

[99  2]


In [107]:
#3.Get every 2nd element, starting from the last and moving backwards.
print(Rev_arr1[-1::-2])

#Exercise End

[34  2 21 99]


In [108]:
#Stats
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [110]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [113]:
#Exercise: Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.
#min
print("min = ", np.min(nums).round(2))

min =  0.0


In [114]:
#max
print("max = ", np.max(nums).round(2))

max =  3.83


In [115]:
#sum
print("sum = ", np.sum(nums).round(2))

max =  30.66


In [123]:
#mean
print("mean = ", np.mean(nums).round(2))

mean =  1.92


In [124]:
#median
print("median = ", np.median(nums).round(2))

median =  1.92


In [120]:
#Variance
print("variance = ", np.var(nums).round(2))

variance =  1.39


In [122]:
#Standard Deviation
print("Standard Deviation  = ", np.std(nums).round(2)) 

Standard Deviation  =  1.18


In [125]:
#Random
#With np.random, we can generate a number of types of dataset, and create training data.
#The below code simulates a fair coin toss.
flip = np.random.choice([0,1], 10)
flip

array([1, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [126]:
np.random.rand(10,20,9)

array([[[3.82021043e-02, 3.27109411e-01, 6.14767059e-01, ...,
         4.91773177e-01, 5.20545311e-01, 7.99032553e-01],
        [6.00994345e-01, 9.36883352e-01, 3.44260924e-01, ...,
         5.16903544e-01, 3.96933573e-02, 6.14368476e-01],
        [2.92655567e-02, 9.67609051e-01, 6.71230326e-01, ...,
         2.81363645e-01, 4.14327937e-01, 8.95761697e-01],
        ...,
        [7.43400949e-01, 6.44433800e-01, 9.12013766e-01, ...,
         7.22959934e-01, 3.99477932e-01, 5.21460712e-01],
        [9.57853176e-02, 5.99847697e-01, 7.50296735e-01, ...,
         1.93064375e-01, 5.90523715e-01, 2.10844975e-01],
        [3.94056143e-01, 4.62606901e-01, 7.31183509e-01, ...,
         8.22084381e-01, 6.49898910e-01, 4.51180947e-01]],

       [[7.74304523e-01, 8.88085970e-01, 2.48762529e-01, ...,
         9.61854953e-01, 6.32184543e-01, 8.21919822e-01],
        [6.64867576e-01, 5.75810366e-01, 9.71572531e-02, ...,
         8.78497976e-01, 7.84902656e-01, 9.22076815e-01],
        [9.64329128e-01, 

In [128]:
#We can produce 1000 datapoints of a normally distributed data set by using np.random.normal()
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([-8.73001989e-02, -6.69960088e-02, -1.08625037e-01, -4.34932050e-02,
        1.45164351e-01, -7.75250920e-02,  8.09383817e-02,  1.02367814e-02,
       -2.71040640e-02, -5.26033762e-03,  2.38594884e-02, -9.40647047e-02,
       -1.48763458e-01,  1.78741438e-01,  6.40234326e-02, -1.96319156e-02,
       -5.14310071e-03, -2.23225971e-02,  2.49536526e-02, -1.22217051e-01,
        7.92570969e-02, -4.61161976e-02,  1.81263450e-01, -1.37593293e-02,
        8.73070975e-02, -7.45169875e-02, -2.21509597e-01, -3.61743453e-02,
       -4.69731912e-02,  1.26776897e-02, -1.78025128e-01,  1.57274278e-01,
        2.33381060e-02,  8.69911367e-03,  5.46060691e-02,  3.61140988e-02,
       -2.11015349e-02, -1.68462559e-02,  4.96780276e-02, -7.90499566e-02,
       -1.19628833e-01, -2.45157741e-01, -1.90740221e-02, -1.34247583e-01,
       -1.54349461e-01, -1.56216030e-01, -7.86759445e-02, -6.89895215e-02,
        6.86141294e-02, -8.55401845e-02,  1.70967308e-02,  4.77699295e-02,
       -5.46973382e-03,  

In [129]:
#Exercise:1.Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
dice = np.random.choice([1,6], 10)
dice


array([6, 6, 6, 6, 1, 1, 6, 1, 6, 6])

In [133]:
#2.Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.
coin = np.random.choice(['H','H','T'], 2)
coin


array(['T', 'T'], dtype='<U1')